# Generated by Django 5.2.17 on 2026-10-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identities', '0003_validate_admin_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interface_palette',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('pink', 'pink'), ('red', 'red')], default='green', max_length=5),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('interface_palette__in', ('green', 'blue', 'pink', 'red'))), name='identity_interface_palette_allowed'),
        ),
    ]
