# Generated by Django 5.2.18 on 2026-10-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('identities', '0004_user_interface_palette_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='identity_interface_palette_allowed',
        ),
        migrations.AlterField(
            model_name='user',
            name='interface_palette',
            field=models.CharField(choices=[('green', 'green'), ('blue', 'blue'), ('pink', 'pink'), ('red', 'red'), ('indigo', 'indigo'), ('violet', 'violet'), ('orange', 'orange'), ('amber', 'amber'), ('emerald', 'emerald'), ('turquoise', 'turquoise')], default='green', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('interface_palette__in', ('green', 'blue', 'pink', 'red', 'indigo', 'violet', 'orange', 'amber', 'emerald', 'turquoise'))), name='identity_interface_palette_allowed'),
        ),
    ]
