# Generated by Django 5.2.17 on 2026-09-27 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('index', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('index__gte', 1)), name='evaluation_index_gte_1')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.evaluation')),
            ],
            options={
                'ordering': ('index', 'pk'),
                'constraints': [models.CheckConstraint(condition=models.Q(('index__gte', 1)), name='question_index_gte_1'), models.UniqueConstraint(fields=('evaluation', 'index'), name='question_index_unique_per_evaluation')],
            },
        ),
    ]
