# Generated by Django 5.2.17 on 2026-09-28 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_require_evaluation_organization'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('immediate', 'Tout de suite'), ('fixed', 'À date fixe'), ('monthly', 'Mensuelle'), ('quarterly', 'Trimestrielle')], max_length=12)),
                ('first_due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='assessments.evaluation')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_schedules', to='teams.team')),
            ],
            options={
                'ordering': ('first_due_date', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('team', 'evaluation'), name='schedule_unique_per_team_evaluation')],
            },
        ),
    ]
