# Generated by Django 5.2.17 on 2026-09-28 22:52

from django.db import migrations, models


def copy_first_due_date(apps, schema_editor):
    schedule = apps.get_model('assessments', 'EvaluationSchedule')
    schedule.objects.update(next_due_date=models.F('first_due_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0004_evaluationschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationschedule',
            name='next_due_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.RunPython(copy_first_due_date, migrations.RunPython.noop),
    ]
