# Generated by Django 5.2.17 on 2026-10-05 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_evaluation_status'),
        ('identities', '0003_validate_admin_organization'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('organization_name', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
                ('evaluation_name', models.CharField(max_length=255)),
                ('assignee_name', models.CharField(max_length=150)),
                ('state', models.CharField(choices=[('not_started', 'À passer'), ('in_progress', 'En cours'), ('completed', 'Complétée')], default='not_started', max_length=12)),
                ('completed_by_name', models.CharField(blank=True, max_length=150)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('revised_by_name', models.CharField(blank=True, max_length=150)),
                ('revised_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.evaluation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='identities.organization')),
                ('revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revised_evaluation_runs', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='assessments.evaluationschedule')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='teams.team')),
            ],
            options={
                'ordering': ('due_date', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='EvaluationRunQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.CharField(max_length=255)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.evaluationrun')),
                ('source_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='assessments.question')),
            ],
            options={
                'ordering': ('index', 'pk'),
            },
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.UniqueConstraint(fields=('schedule', 'due_date'), name='run_schedule_due_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ['not_started', 'in_progress', 'completed'])), name='evaluation_run_state_valid'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('completed_by__isnull', True), ('completed_by_name', ''), ('state__in', ('not_started', 'in_progress'))), models.Q(('completed_at__isnull', False), ('state', 'completed'), models.Q(('completed_by_name', ''), _negated=True)), _connector='OR'), name='evaluation_run_completion_consistent'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrun',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('revised_at__isnull', True), ('revised_by__isnull', True), ('revised_by_name', '')), models.Q(('revised_at__isnull', False), ('state', 'completed'), models.Q(('revised_by_name', ''), _negated=True), ('revised_at__gte', models.F('completed_at'))), _connector='OR'), name='evaluation_run_revision_consistent'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrunquestion',
            constraint=models.UniqueConstraint(fields=('run', 'source_question'), name='run_source_question_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrunquestion',
            constraint=models.UniqueConstraint(fields=('run', 'index'), name='run_question_index_unique'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrunquestion',
            constraint=models.CheckConstraint(condition=models.Q(('index__gte', 1)), name='run_question_index_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='evaluationrunquestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), ('score__range', (0, 10)), _connector='OR'), name='run_question_score_0_10'),
        ),
    ]
