# Generated by Django 5.2.17 on 2026-10-05 13:02

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_existing_expected_evaluations'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluationrunquestion',
            name='run_question_score_0_10',
        ),
        migrations.AddConstraint(
            model_name='evaluationrunquestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__isnull', True), models.Q(('score__range', (0, 10)), ('score', django.db.models.functions.comparison.Cast(models.F('score'), models.IntegerField()))), _connector='OR'), name='run_question_score_0_10'),
        ),
    ]
