# Generated by Django 5.2.18 on 2026-10-06 21:49

from django.db import migrations, models
from django.db.models import Q


def flag_unavailable_assignees(apps, schema_editor):
    Schedule = apps.get_model("assessments", "EvaluationSchedule")
    Schedule.objects.using(schema_editor.connection.alias).filter(
        Q(assignee__is_active=False) | Q(assignee__isnull=True)
    ).exclude(mode__in=("immediate", "fixed"), runs__state="completed").update(
        requires_reassignment=True
    )


class Migration(migrations.Migration):
    dependencies = [
        ("assessments", "0013_question_lineage"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationschedule",
            name="requires_reassignment",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flag_unavailable_assignees, migrations.RunPython.noop),
    ]
