# Generated by Django 5.2.18 on 2026-10-08 22:01

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_evaluationschedule_requires_reassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrunquestion',
            name='score_guides',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.CreateModel(
            name='QuestionScoreGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField()),
                ('text', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_guides', to='assessments.question')),
            ],
            options={
                'ordering': ('score',),
                'constraints': [models.UniqueConstraint(fields=('question', 'score'), name='question_score_guide_unique'), models.CheckConstraint(condition=models.Q(('score__range', (0, 10)), ('score', django.db.models.functions.comparison.Cast(models.F('score'), models.IntegerField()))), name='question_score_guide_integer_0_10'), models.CheckConstraint(condition=models.Q(('text', ''), _negated=True), name='question_score_guide_nonempty')],
            },
        ),
    ]
