# Generated by Django 5.2.18 on 2026-10-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_evaluationschedule_requires_reassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationrunquestion',
            name='appreciation_markers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='question',
            name='appreciation_markers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
