# Generated by Django 5.2.17 on 2026-09-28 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identities', '0003_validate_admin_organization'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('organization_created', 'Organisation créée'), ('organization_renamed', 'Organisation renommée'), ('organization_deleted', 'Organisation supprimée'), ('member_assigned', 'Membre affecté'), ('member_removed', 'Membre retiré'), ('user_invited', 'Utilisateur invité'), ('user_updated', 'Utilisateur modifié'), ('user_role_changed', 'Fonction modifiée'), ('user_deactivated', 'Utilisateur désactivé'), ('user_reactivated', 'Utilisateur réactivé'), ('user_deleted', 'Utilisateur supprimé'), ('team_created', 'Équipe créée'), ('team_renamed', 'Équipe renommée'), ('team_archived', 'Équipe archivée'), ('coach_assigned', 'Coach affecté'), ('coach_removed', 'Coach retiré'), ('evaluation_created', 'Évaluation créée'), ('evaluation_renamed', 'Évaluation renommée'), ('evaluation_deleted', 'Évaluation supprimée'), ('question_created', 'Question créée'), ('question_updated', 'Question modifiée'), ('question_deleted', 'Question supprimée')], max_length=40)),
                ('description', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identities.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='ErrorEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('organization_name', models.CharField(blank=True, max_length=255)),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('team_name', models.CharField(blank=True, max_length=255)),
                ('operation', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('correlation_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='identities.organization')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='teams.team')),
            ],
            options={
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
