# Generated by Django 5.2.17 on 2026-10-05 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_alter_activityentry_action'),
        ('journals', '0007_logentry_evaluation_logentry_evaluation_name_and_more'),
    ]

    operations = [
    ]
